project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About Me
        #icon: megaphone
    tools:
      - icon: github
        href: https://github.com/Juandmar-bit
        

format:
  html:
    backgroundcolor: "#002242"
    fontcolor: "white"
    linkcolor: "#8ecae6"
    mainfont: "monospace"
    fontsize: 20px
    theme:
      - cosmo
      - brand
      
    highlight-style: atom-one-dark
    css: styles.css
    toc: true

editor: visual

